#!/usr/bin/env python3
"""Generate board pin map C source from tools/pinmap/<board>.csv."""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path


@dataclass
class PinMap:
    board: str = ""
    mcu: str = ""
    package: str = ""
    periph: list[tuple[str, str]] = field(default_factory=list)
    gpio: list[tuple[str, str]] = field(default_factory=list)


def parse_pin_name(pin_name: str) -> tuple[str, int]:
    name = pin_name.strip().lower()
    if name.startswith("p"):
        name = name[1:]
    if len(name) < 2 or name[0] not in "abcdefghi":
        raise ValueError(f"invalid pin name: {pin_name!r}")
    num = int(name[1:])
    if num < 0 or num > 15:
        raise ValueError(f"pin number out of range: {pin_name!r}")
    return name[0], num


def pin_to_hal(pin_name: str) -> tuple[str, str]:
    bank, num = parse_pin_name(pin_name)
    return f"GPIO{bank.upper()}", f"GPIO_PIN_{num}"


def load_csv(path: Path) -> PinMap:
    text = path.read_text(encoding="utf-8")
    pm = PinMap()
    section = "meta"

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if line.startswith("@"):
            key, _, value = line.partition(",")
            key = key[1:].strip().lower()
            value = value.strip()
            if key == "board":
                pm.board = value
            elif key == "mcu":
                pm.mcu = value
            elif key == "package":
                pm.package = value
            continue

        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip().lower()
            continue

        row = next(csv.reader(StringIO(line)))
        if not row:
            continue

        if section == "periph":
            if row[0].lower() in {"signal", "name"}:
                continue
            if len(row) < 2:
                raise ValueError(f"periph row needs signal,pin: {line!r}")
            pm.periph.append((row[0].strip(), row[1].strip()))
        elif section == "gpio":
            if row[0].lower() in {"pin", "name"}:
                continue
            if len(row) < 1:
                continue
            pin = row[0].strip()
            alias = row[1].strip() if len(row) > 1 else ""
            pm.gpio.append((pin, alias))
        elif section == "meta" and row[0].lower() == "gpio":
            pin = row[1].strip()
            alias = row[2].strip() if len(row) > 2 else ""
            pm.gpio.append((pin, alias))
        elif section == "meta" and len(row) >= 2 and row[0].lower() != "gpio":
            pm.periph.append((row[0].strip(), row[1].strip()))

    if not pm.board:
        pm.board = path.stem
    if not pm.mcu:
        raise ValueError(f"missing @mcu in {path}")
    if not pm.package:
        raise ValueError(f"missing @package in {path}")
    if not pm.gpio:
        raise ValueError(f"no [gpio] entries in {path}")

    return pm


def c_string(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return f"\"{value}\""


def render_c(pm: PinMap, source: Path) -> str:
    gpio_rows: list[str] = []
    for pin, alias in pm.gpio:
        port, hal_pin = pin_to_hal(pin)
        gpio_rows.append(
            f"  {{ {c_string(pin)}, {c_string(alias or None)}, {port}, {hal_pin} }},"
        )

    periph_rows = [
        f"  {{ {c_string(signal)}, {c_string(pin)} }},"
        for signal, pin in pm.periph
    ]

    periph_body = "\n".join(periph_rows)
    if not periph_body:
        periph_body = ""

    return f"""/* AUTO-GENERATED by tools/pinmap/pinmap-gen.py — do not edit */
/* Source: {source.as_posix()} */

#include "tars_mcu_pinmap.h"
#include "main.h"

static const tars_mcu_gpio_entry_t s_gpio[] = {{
{chr(10).join(gpio_rows)}
}};

static const tars_mcu_periph_entry_t s_periph[] = {{
{periph_body}
}};

const char *TarsMcuPinmap_BoardId(void)
{{
  return "{pm.board}";
}}

const char *TarsMcuPinmap_McuId(void)
{{
  return "{pm.mcu}";
}}

const char *TarsMcuPinmap_PackageId(void)
{{
  return "{pm.package}";
}}

const tars_mcu_gpio_entry_t *TarsMcuPinmap_GetGpioTable(uint32_t *count_out)
{{
  if (count_out != NULL)
  {{
    *count_out = (uint32_t)(sizeof(s_gpio) / sizeof(s_gpio[0]));
  }}

  return s_gpio;
}}

const tars_mcu_periph_entry_t *TarsMcuPinmap_GetPeriphTable(uint32_t *count_out)
{{
  if (count_out != NULL)
  {{
    *count_out = (uint32_t)(sizeof(s_periph) / sizeof(s_periph[0]));
  }}

  return s_periph;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path, help="Board pin map CSV")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output .c path")
    args = parser.parse_args()

    pm = load_csv(args.csv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_c(pm, args.csv), encoding="utf-8")
    print(f"generated {args.output} ({len(pm.gpio)} gpio, {len(pm.periph)} periph)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
