#!/usr/bin/env python3
"""Sync the Simulink/Embedded-Coder FOC controller into generated/foc/.

The motor-control algorithm is owned by the Simulink project
(motor-ctrl-sim). That project's `gen_code.m` emits portable single-precision
C into `codegen_stm32/`, which is the deliverable and is treated here as a
read-only source of truth: this firmware *references* it and never edits it.

This mirrors the pin map / probe code-gen flow:

    motor-ctrl-sim/codegen_stm32/  (source of truth, never edited)
        --> tools/foc/foc-sync.py  (copy, build time)
        --> generated/foc/         (gitignored, referenced by CMake)

Only the files needed to compile the controller are copied (the *.c/*.h of
the generated module plus rtwtypes.h); MATLAB build artifacts (*.mat, *.mk,
reports, examples) are left behind.

Resolution order for the source directory:
  1. --src CLI argument
  2. $TARS_FOC_CODEGEN_DIR
  3. the default sibling checkout (../motor-ctrl/motor-ctrl-sim/codegen_stm32)

If the source is unavailable but `generated/foc/` is already populated from a
previous sync, the existing copy is kept (a warning is printed) so the
firmware still builds without the Simulink checkout present.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path

# Entry point + its support files. Globs keep this robust to Embedded Coder
# splitting helpers across foc_step_stm32_*.{c,h} between MATLAB versions.
SOURCE_GLOBS = ("foc_step_stm32*.c", "foc_step_stm32*.h", "rtwtypes.h")

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SRC = REPO_ROOT.parent / "motor-ctrl" / "motor-ctrl-sim" / "codegen_stm32"

# mc_params.m scalars mirrored into firmware (motor/board values the firmware
# needs for peripheral config + sanity). name -> (macro, c_type, default).
MC_PARAMS = {
    "Fpwm":       ("FOC_PARAM_FPWM_HZ",         "int",   "20000"),
    "Nspeed":     ("FOC_PARAM_NSPEED",          "int",   "10"),
    "Vdc":        ("FOC_PARAM_VDC_V",           "float", "24.0f"),
    "Imax":       ("FOC_PARAM_IMAX_A",          "float", "5.0f"),
    "PolePairs":  ("FOC_PARAM_POLE_PAIRS",      "int",   "4"),
    "RatedSpeed": ("FOC_PARAM_RATED_SPEED_RPM", "int",   "3000"),
    "RatedPower": ("FOC_PARAM_RATED_POWER_W",   "int",   "60"),
}


def resolve_src(cli_src: str | None) -> Path | None:
    for candidate in (cli_src, os.environ.get("TARS_FOC_CODEGEN_DIR"), str(DEFAULT_SRC)):
        if candidate:
            p = Path(candidate).expanduser()
            if p.is_dir():
                return p.resolve()
    return None


def collect(src: Path) -> list[Path]:
    files: list[Path] = []
    for pattern in SOURCE_GLOBS:
        files.extend(sorted(src.glob(pattern)))
    # de-dup while preserving order
    seen: set[str] = set()
    unique: list[Path] = []
    for f in files:
        if f.name not in seen:
            seen.add(f.name)
            unique.append(f)
    return unique


def parse_mc_params(path: Path) -> dict[str, str]:
    """Pull the whitelisted scalar assignments (Name = value;) from mc_params.m."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    text = path.read_text(encoding="utf-8")
    for name in MC_PARAMS:
        m = re.search(rf"^\s*{re.escape(name)}\s*=\s*([-+0-9.eE]+)\s*;", text, re.MULTILINE)
        if m:
            values[name] = m.group(1)
    return values


def render_foc_params_h(values: dict[str, str], source: Path | None) -> str:
    lines = [
        "/* AUTO-GENERATED by tools/foc/foc-sync.py - do not edit */",
        f"/* Source: {source.as_posix() if source else '(defaults; mc_params.m not found)'} */",
        "/* Motor/board constants mirrored from the Simulink single source of",
        "   truth (mc_params.m) so firmware peripheral config stays in sync. */",
        "",
        "#ifndef FOC_PARAMS_H",
        "#define FOC_PARAMS_H",
        "",
    ]
    for name, (macro, ctype, default) in MC_PARAMS.items():
        raw = values.get(name)
        if raw is None:
            val = default
        elif ctype == "float":
            s = raw
            if not s.endswith(("f", "F")):
                if not any(c in s for c in ".eE"):
                    s += ".0"
                s += "f"
            val = s
        else:
            val = str(int(float(raw)))
        lines.append(f"#define {macro:<28} {val}")
    lines += ["", "#endif /* FOC_PARAMS_H */", ""]
    return "\n".join(lines)


def sync(src: Path, out: Path) -> int:
    files = collect(src)
    if not files:
        print(f"error: no FOC sources matched in {src}", file=sys.stderr)
        return 1

    out.mkdir(parents=True, exist_ok=True)
    for f in files:
        shutil.copy2(f, out / f.name)

    # Mirror motor/board params from mc_params.m (sibling of codegen_stm32).
    mc_path = src.parent / "mc_params.m"
    mc_values = parse_mc_params(mc_path)
    (out / "foc_params.h").write_text(
        render_foc_params_h(mc_values, mc_path if mc_values else None),
        encoding="utf-8",
    )
    print(f"  foc_params.h from {mc_path if mc_values else 'defaults'} "
          f"({len(mc_values)}/{len(MC_PARAMS)} params)")

    stamp = out / "FOC_SOURCE.txt"
    stamp.write_text(
        "# AUTO-GENERATED by tools/foc/foc-sync.py - do not edit\n"
        f"source: {src.as_posix()}\n"
        f"files: {', '.join(f.name for f in files)}\n",
        encoding="utf-8",
    )
    print(f"synced {len(files)} FOC source(s) from {src} -> {out}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", help="codegen_stm32 directory (overrides env/default)")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output dir (generated/foc)")
    args = parser.parse_args()

    src = resolve_src(args.src)
    if src is None:
        existing = list(args.output.glob("foc_step_stm32*.c")) if args.output.is_dir() else []
        if existing:
            print(
                "warning: FOC codegen source not found; keeping existing "
                f"generated/foc copy ({len(existing)} file(s)). "
                "Set TARS_FOC_CODEGEN_DIR or --src to re-sync.",
                file=sys.stderr,
            )
            return 0
        print(
            "error: FOC codegen source not found and generated/foc is empty.\n"
            "  Point at the Simulink output via --src <dir> or "
            "TARS_FOC_CODEGEN_DIR=<dir>\n"
            f"  (default tried: {DEFAULT_SRC})",
            file=sys.stderr,
        )
        return 1

    return sync(src, args.output)


if __name__ == "__main__":
    sys.exit(main())
