#!/usr/bin/env python3
"""Generate probe metric table C source from tools/probe/metrics.csv."""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path


@dataclass
class Metrics:
    board: str = ""
    rows: list[tuple[str, str, str, int]] = field(default_factory=list)


def load_csv(path: Path) -> Metrics:
    text = path.read_text(encoding="utf-8")
    m = Metrics()
    section = "meta"

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if line.startswith("@"):
            key, _, value = line.partition(",")
            if key[1:].strip().lower() == "board":
                m.board = value.strip()
            continue

        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip().lower()
            continue

        if section != "metrics":
            continue

        row = next(csv.reader(StringIO(line)))
        if not row or row[0].lower() == "name":
            continue
        if len(row) < 3:
            raise ValueError(f"metric row needs name,unit,provider[,arg]: {line!r}")

        name = row[0].strip()
        unit = row[1].strip()
        provider = row[2].strip().upper()
        arg = int(row[3].strip()) if len(row) > 3 and row[3].strip() else 0
        m.rows.append((name, unit, provider, arg))

    if not m.rows:
        raise ValueError(f"no [metrics] rows in {path}")

    return m


def render_c(m: Metrics, source: Path) -> str:
    rows = "\n".join(
        f'  {{ "{name}", "{unit}", TARS_PROBE_SRC_{prov}, {arg}U }},'
        for name, unit, prov, arg in m.rows
    )

    return f"""/* AUTO-GENERATED by tools/probe/probe-gen.py — do not edit */
/* Source: {source.as_posix()} */

#include "tars_probe_metrics.h"

const tars_probe_metric_t g_probe_metrics[] = {{
{rows}
}};

const uint32_t g_probe_metric_count =
    (uint32_t)(sizeof(g_probe_metrics) / sizeof(g_probe_metrics[0]));
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args()

    m = load_csv(args.csv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_c(m, args.csv), encoding="utf-8")
    print(f"generated {args.output} ({len(m.rows)} metrics)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
