#ifndef TARS_FOC_H
#define TARS_FOC_H

#include <stdint.h>

/*
 * TARS FOC driver  --  firmware-resident control surface around the portable
 * single-precision FOC controller generated by the Simulink project
 * (generated/foc/foc_step_stm32.c, synced by tools/foc/foc-sync.py and never
 * hand-edited).
 *
 * Layering (see App/resource/tars_resource.h): the 20 kHz current loop is a
 * high-rate, IRQ-driven peripheral and therefore owns its own driver here.
 * The resource layer / apps only touch the *control surface* below
 * (setpoints + telemetry snapshot), exactly like GPIO.
 *
 * Hardware bring-up status: TIM1 is currently a plain base timer and no ADC is
 * configured in the CubeMX project, so the real PWM/ADC path is compiled out
 * behind TARS_FOC_DRIVE_PWM (default 0).  With it disabled the controller is
 * still linked and exercised (TarsFoc_Step) so the Simulink->firmware workflow
 * is closed end to end; nothing drives the inverter.  Enable TARS_FOC_DRIVE_PWM
 * only after the TIM1 advanced-PWM + ADC-injected bring-up lands.
 */

typedef enum {
  TARS_FOC_STATE_IDLE  = 0,
  TARS_FOC_STATE_RUN   = 1,
  TARS_FOC_STATE_FAULT = 2
} tars_foc_state_t;

typedef struct {
  float    theta_est_rad;   /* estimated electrical angle [rad]      */
  float    speed_est_rpm;   /* estimated mechanical speed [rpm]      */
  float    speed_ref_rpm;   /* commanded speed [rpm]                 */
  float    id;              /* d-axis current [A]                    */
  float    iq;              /* q-axis current [A]                    */
  float    vdc;             /* DC-bus voltage [V]                    */
  float    ia;              /* phase A current [A]                   */
  float    ib;              /* phase B current [A]                   */
  float    ic;              /* phase C current [A]                   */
  float    duty_a;          /* TIM1 CH1 duty [0,1]                   */
  float    duty_b;          /* TIM1 CH2 duty [0,1]                   */
  float    duty_c;          /* TIM1 CH3 duty [0,1]                   */
  uint32_t loop_count;      /* control iterations since init         */
  uint8_t  enabled;         /* 1 = controller enabled                */
  uint8_t  state;           /* tars_foc_state_t                      */
  uint8_t  fault_code;      /* 0 = none                              */
} tars_foc_snapshot_t;

/* One-time init: zeroes controller state. Does NOT start TIM1/ADC. */
void TarsFoc_Init(void);

/* Start TIM1/ADC for FOC (bridge still off until TarsFoc_Enable). */
void TarsFoc_BootHw(void);

/* Control surface (thread-safe). */
void TarsFoc_SetSpeedRef(float rpm);
void TarsFoc_Enable(int enable);
void TarsFoc_GetSnapshot(tars_foc_snapshot_t *out);

/* Arm zero-current ADC offset calibration. Averages samples with the bridge
 * off; call when the power stage is up and the motor is at rest. */
void TarsFoc_Calibrate(void);

/* Low-rate housekeeping, called from the resource task. When the real PWM
 * path is disabled this also runs one bench controller step so telemetry and
 * the Simulink->firmware integration stay live (see note above). */
void TarsFoc_Step(void);

/* 20 kHz current-loop entry point. Hook to the TIM1 update / ADC injected-EOC
 * ISR once TARS_FOC_DRIVE_PWM is enabled; a no-op until then. */
void TarsFoc_ControlLoopISR(void);

#endif /* TARS_FOC_H */
